######################################################################
# Automatically generated by qmake (2.01a) Tue Jul 16 10:24:50 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += gui
QT += widgets

# Input
SOURCES += hello.cpp
